In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv(r"C:\Users\sutra\Downloads\Advanced_Retail_Sales_Dataset_Cleaned_1030rows.csv")

In [5]:
df.shape

(1030, 14)

In [7]:
df.columns

Index(['Sale_ID', 'Sale_Date', 'Customer_ID', 'Order_ID', 'Product_ID',
       'Quantity', 'Cost_Price', 'Selling_Price', 'Discount_%', 'Revenue',
       'Profit', 'State', 'Country', 'Sales_Channel'],
      dtype='object')

In [8]:
product_details = df[                                           #Extract Product Information
    [ "Product_ID",
      "Selling_Price",] ]

product_details.head()

  Product_ID  Selling_Price
0   SKU-1950         187.16
1   SKU-2013         181.75
2   SKU-2688          77.67
3   SKU-6924         360.18
4   SKU-2199         475.39

In [9]:
price = df[                                         #Extract Price Information
    [
        "Product_ID",
        "Cost_Price",
        "Selling_Price",
        "Profit"
    ]
]

price.head()

  Product_ID  Cost_Price  Selling_Price  Profit
0   SKU-1950      160.96         187.16  -33.70
1   SKU-2013      100.06         181.75  163.38
2   SKU-2688       61.98          77.67   55.46
3   SKU-6924      201.08         360.18  492.33
4   SKU-2199      212.45         475.39  720.46

NameError: name 'State' is not defined