In [71]:
import pandas as pd

In [144]:
df = pd.read_csv(r"C:\Users\sutra\Downloads\Advanced_Retail_Sales_Dataset_Messy_1030rows_19cols.csv")

In [145]:
df.head()

,Sale_ID,Sale_Date,Customer_ID,Order_ID,Product_ID,Category,Quantity,Cost_Price,Selling_Price,Discount_%,Revenue,Profit,Payment_Method,City,State,Country,Sales_Channel,Returned,Customer_Rating
0,1,12/7/2022,CUST-57931,ORD-711097,SKU-1950,Home & Kitchen,3,160.96,187.16,20,449.18,-33.70,Credit Card,Chicago,IL,USA,Online,NaN,NaN
1,2,04/3/2025,CUST-26226,ORD-334083,SKU-2013,Books,2,100.06,181.75,0,363.50,163.38,Cash,Houston,TX,USA,Online,NaN,NaN
2,3,21/2/2025,CUST-99391,ORD-289505,SKU-2688,Groceries,7,61.98,77.67,10,489.32,55.46,Debit Card,Chicago,IL,USA,Online,NaN,NaN
3,4,11/8/2024,CUST-86750,ORD-575198,SKU-6924,Beauty,4,201.08,360.18,10,1296.65,492.33,Credit Card,Miami,FL,USA,Online,NaN,NaN
4,5,08/7/2024,CUST-47740,ORD-738539,SKU-2199,Clothing,5,212.45,475.39,25,1782.71,720.46,Wallet,Miami,FL,USA,Store,NaN,NaN

In [146]:
df.shape

(1030, 19)

In [147]:
df.isnull().sum() #count missing/null values

Sale_ID               0
Sale_Date             0
Customer_ID           0
Order_ID              0
Product_ID            0
Category             12
Quantity              0
Cost_Price            0
Selling_Price         0
Discount_%            0
Revenue               0
Profit                0
Payment_Method       15
City                  7
State                 0
Country               0
Sales_Channel         0
Returned           1030
Customer_Rating    1030
dtype: int64

In [148]:
df.duplicated().sum()

30

In [168]:
df.dropna(axis=0) #remove null rows

,Sale_ID,Sale_Date,Customer_ID,Order_ID,Product_ID,Quantity,Cost_Price,Selling_Price,Discount_%,Revenue,Profit,State,Country,Sales_Channel
0,1,12/7/2022,CUST-57931,ORD-711097,SKU-1950,3,160.96,187.16,20,449.18,-33.70,IL,USA,Online
1,2,04/3/2025,CUST-26226,ORD-334083,SKU-2013,2,100.06,181.75,0,363.50,163.38,TX,USA,Online
2,3,21/2/2025,CUST-99391,ORD-289505,SKU-2688,7,61.98,77.67,10,489.32,55.46,IL,USA,Online
3,4,11/8/2024,CUST-86750,ORD-575198,SKU-6924,4,201.08,360.18,10,1296.65,492.33,FL,USA,Online
4,5,08/7/2024,CUST-47740,ORD-738539,SKU-2199,5,212.45,475.39,25,1782.71,720.46,FL,USA,Store
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1025,707,30/10/2023,CUST-69751,ORD-237733,SKU-9813,8,352.70,650.48,15,4423.26,1601.66,NY,USA,Store
1026,922,24/6/2025,CUST-89491,ORD-851197,SKU-5482,2,110.48,144.93,0,289.86,68.90,FL,USA,Store
1027,305,19/1/2023,CUST-45697,ORD-424433,SKU-8778,5,388.73,820.30,10,3691.35,1747.70,FL,USA,Store
1028,451,19/6/2024,CUST-76913,ORD-516786,SKU-5182,6,206.15,256.61,10,1385.69,148.79,CA,USA,Store
1029,466,27/9/2022,CUST-54115,ORD-490825,SKU-2082,6,359.93,554.46,0,3326.76,1167.18,CA,USA,Online

In [167]:
df.dropna(axis=1) #remove null columns

,Sale_ID,Sale_Date,Customer_ID,Order_ID,Product_ID,Quantity,Cost_Price,Selling_Price,Discount_%,Revenue,Profit,State,Country,Sales_Channel
0,1,12/7/2022,CUST-57931,ORD-711097,SKU-1950,3,160.96,187.16,20,449.18,-33.70,IL,USA,Online
1,2,04/3/2025,CUST-26226,ORD-334083,SKU-2013,2,100.06,181.75,0,363.50,163.38,TX,USA,Online
2,3,21/2/2025,CUST-99391,ORD-289505,SKU-2688,7,61.98,77.67,10,489.32,55.46,IL,USA,Online
3,4,11/8/2024,CUST-86750,ORD-575198,SKU-6924,4,201.08,360.18,10,1296.65,492.33,FL,USA,Online
4,5,08/7/2024,CUST-47740,ORD-738539,SKU-2199,5,212.45,475.39,25,1782.71,720.46,FL,USA,Store
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1025,707,30/10/2023,CUST-69751,ORD-237733,SKU-9813,8,352.70,650.48,15,4423.26,1601.66,NY,USA,Store
1026,922,24/6/2025,CUST-89491,ORD-851197,SKU-5482,2,110.48,144.93,0,289.86,68.90,FL,USA,Store
1027,305,19/1/2023,CUST-45697,ORD-424433,SKU-8778,5,388.73,820.30,10,3691.35,1747.70,FL,USA,Store
1028,451,19/6/2024,CUST-76913,ORD-516786,SKU-5182,6,206.15,256.61,10,1385.69,148.79,CA,USA,Store
1029,466,27/9/2022,CUST-54115,ORD-490825,SKU-2082,6,359.93,554.46,0,3326.76,1167.18,CA,USA,Online

In [155]:
df.shape

(1030, 14)

In [169]:
df.isnull().sum()

Sale_ID          0
Sale_Date        0
Customer_ID      0
Order_ID         0
Product_ID       0
Quantity         0
Cost_Price       0
Selling_Price    0
Discount_%       0
Revenue          0
Profit           0
State            0
Country          0
Sales_Channel    0
dtype: int64

In [134]:
df.dtypes

Sale_ID               int64
Sale_Date            object
Customer_ID          object
Order_ID             object
Product_ID           object
Category           category
Quantity              int64
Cost_Price          float64
Selling_Price       float64
Discount_%            int64
Revenue             float64
Profit              float64
Payment_Method     category
City               category
State              category
Country            category
Sales_Channel      category
Returned            float64
Customer_Rating     float64
dtype: object

In [172]:
df.columns

Index(['Sale_ID', 'Sale_Date', 'Customer_ID', 'Order_ID', 'Product_ID',
       'Quantity', 'Cost_Price', 'Selling_Price', 'Discount_%', 'Revenue',
       'Profit', 'State', 'Country', 'Sales_Channel'],
      dtype='object')

In [175]:
import pandas as pd

# Convert repeated text columns to category
#df["Category"] = df["Category"].astype("category")
#df["Payment_Method"] = df["Payment_Method"].astype("category")
#df["City"] = df["City"].astype("category")
df["State"] = df["State"].astype("category")
df["Country"] = df["Country"].astype("category")
df["Sales_Channel"] = df["Sales_Channel"].astype("category")

In [176]:
# Verify data types
df.dtypes

Sale_ID             int64
Sale_Date          object
Customer_ID        object
Order_ID           object
Product_ID         object
Quantity            int64
Cost_Price        float64
Selling_Price     float64
Discount_%          int64
Revenue           float64
Profit            float64
State            category
Country          category
Sales_Channel    category
dtype: object

In [178]:
df.to_csv(r"C:\Users\sutra\Downloads\Advanced_Retail_Sales_Dataset_Cleaned_1030rows.csv", index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [179]:
df.shape

(1030, 14)